### ISSUE TITLE
Typescript Example

### ISSUE THREAD

**Issue by jakobwgnr** [storyblok/next.js-13-boilerplate#1]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Hey! Current example is JS only - It would be great also to have a TS example.

In general it is also working with typescript, but it is crucial to use the package '@storyblok/react/rsc' and not just '@storyblok/react'...
With '@storyblok/react' you will be receiving an error due to a missing "use client"...
With '@storyblok/react/rsc' you will be receiving an TS error due to missing type declarations within this package. --> You may ignore this and it is still working, but in general it would be great is this package is also fully supported for TS.

Maybe a small hint regarding this in the [How-To](https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-13-in-5-minutes)  would be sufficient?!

Many thanks in advance! 
Jakob

**Comment by arorachakit** [comment]
Hey @jakobwgnr - thank you so much for the suggestion.
We are evaluating the possibility of adding TS examples internally. 

Though if you want to see one now, please take a look at the React SDK - https://github.com/storyblok/storyblok-react
We have all the playgrounds there in TS. Also regarding the hint, we also have that mentioned in the Readme of the same. 

Thanks for the suggestion, we will add a RSC hint to the tutorial as well :) It makes sense to add it there.

**Comment by arorachakit** [comment]
Hey @jakobwgnr !
I also went a bit back to check a couple of things, as your issue is old probably you were not able to see the fixed example in the sdk as well. 
Here is a related issue that should help - https://github.com/storyblok/storyblok-react/issues/613

But we have added the fix to the Playgrounds I mentioned earlier as well. The type declaration is mainly related to the tsconfig. You can see the updated commit to fix that here - https://github.com/storyblok/storyblok-react/commit/a280e59f5e1aa6aed34ae5be2469da4222514eff
